Models/ContactUs.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace AtomHealth.Models
{
    public class ContactUs
    {
        [Required(ErrorMessage = "Name cannot be blank.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Email Address can not be blank.")]
        [Display(Name = "Email Address")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Please Enter Valid Email Address.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Subject cannot be blank.")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "Message cannot be blank.")]
        public string Message { get; set; }
    }
}

Models/News.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AtomHealth.Models
{
    public class News
    {
        public class Source
        {
            public string id { get; set; }
            public string name { get; set; }
        }

        public class Article
        {
            public Source source { get; set; }
            public string author { get; set; }
            public string title { get; set; }
            public string description { get; set; }
            public string url { get; set; }
            public string urlToImage { get; set; }
            public DateTime publishedAt { get; set; }
            public string content { get; set; }
        }

        public class Example
        {
            public string status { get; set; }
            public int totalResults { get; set; }
            public IList<Article> articles { get; set; }
        }


    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AtomHealth.Models;
using System.Net;
using Newtonsoft.Json;
using static AtomHealth.Models.News;

namespace AtomHealth.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult OurSolution()
        {
            return View();
        }

        public IActionResult JoinUs()
        {
            return View();
        }

        public IActionResult FAQ()
        {
            return View();
        }

        public IActionResult ContactUs()
        {
            return View();
        }

        public IActionResult News()
        {
            string url = string.Format("http://newsapi.org/v2/top-headlines?country=ca&category=health&apiKey=aa93bb23607b4762b8ce8a1704b8e5cb");


            using (WebClient client = new WebClient())
            {
                string json = client.DownloadString(url);
                var jsonstring = JsonConvert.DeserializeObject<Example>(json);

                var a = jsonstring.articles;

                return View(a);
            }
        }

        public IActionResult Patient()
        {
            return View();
        }

        public IActionResult Doctor()
        {
            return View();
        }

        public IActionResult EMR()
        {
            return View();
        }

        public IActionResult Insurance()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SubscribeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AtomHealth.Areas.Identity.Data;
using AtomHealth.Areas.Identity.Pages.Account;
using AtomHealth.Data;
using AtomHealth.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AtomHealth.Controllers
{
    public class SubscribeController : Controller
    {
        private readonly ConnectionDB _context;

        public SubscribeController(ConnectionDB context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.positionid = HttpContext.Session.GetString("positionid");
            if (ViewBag.positionid == "1")
            {
                ViewBag.firstname = HttpContext.Session.GetString("firstname");

                return View(_context.tblSubscribe.ToList());
            }
            return RedirectToAction("Signin", "SignUpAtom");
          
        }

        [HttpPost]
        public IActionResult Create(Subscribe s)
        {
            Subscribe tblS = new Subscribe();
            var target = _context.tblSubscribe.Where(x => x.email == s.email).FirstOrDefault();
            if(target!=null)
            {
                ViewBag.alreadysub = "We already have your email address on our subscription list. Thanks!";
                return View();
            }
            else
            {
                tblS.email = s.email;
                _context.tblSubscribe.Add(tblS);
                _context.SaveChanges();
                ViewBag.msg = " You are now Subscribed. Thanks!";
                return View();
            }           
        }
    }
}

Views/Home/ContactUs.cshtml
@model AtomHealth.Models.ContactUs
@{
    ViewData["Title"] = "Contact Us";
    
}
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<link rel="stylesheet" href="~/css/site.css" />


<h1 style="color:#42a5ff; font-size:24px; font-weight:bold">Contact Form</h1>
<hr />


@if (ViewBag.Message == null)
{
    <p1 style="color:#42a5ff; font-size:16px;">Say hello to us if you do not have any concerns!</p1>
    <div class="containerforcontactform">
        <form method="post" style="margin-bottom:55px;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div>
                Full Name
                <input asp-for="Name" class="form-control" placeholder="Your Full Name..">
                <span class="text-danger" asp-validation-for="@Model.Name"></span>
            </div>
            <div>
                Subject
                <input asp-for="Subject" class="form-control" placeholder="Your Subject..">
                <span class="text-danger" asp-validation-for="@Model.Subject"></span>
            </div>
            <div>
                Email
                <input asp-for="Email" class="form-control" placeholder="Your Email Address..">
                <span class="text-danger" asp-validation-for="@Model.Email"></span>
            </div>
            <div>
                Message
                <textarea asp-for="Message" class="form-control" placeholder="Write something.." style="height:200px"></textarea>
                <span class="text-danger" asp-validation-for="@Model.Message"></span>
            </div>
            <input type="submit" value="Submit">
        </form>
    </div>
}
<div>
    @if (ViewBag.Message != null)
    {
        <h2>@ViewBag.Message</h2>


    }
</div>

Views/Home/Doctor.cshtml
<link rel="stylesheet" href="~/css/site.css" />
@{
    ViewData["Title"] = "For Doctors";
 @*Layout = "~/Views/Shared/_LayoutForSubPages.cshtml";*@
}

<img src="~/images/doctortwo.jpg" style="width:100%; height:350px; margin-bottom:20px; border-radius:15px;" />

<h1 style="color:#42a5ff; font-size:24px; font-weight:bold">Information to Doctors</h1>
<hr />
<p style="font-size:18px; line-height:20px; margin-bottom:15px;">
    Changing times call for newer, functional solutions. Virtual care, being peripheral since a long time, suddenly found acceptance and adoption during these unprecedented times.
    As a physician, your Hippocratic Oath puts you in a position where you have to adopt new technology for the patients, while being mindful of their privacy rights, as you pursue your goal of patient well-being and best possible outcomes. As you juggle in-person clinical visits and virtual telemedicine visits, we help you maintain your peace of mind by enabling simple, concise health information sharing. Improved patient outcomes, reduced liability and more reliable decision-making for a patient are just a few benefits. Ask your telehealth provider to connect with us to enable secure data access.
</p>
<p style="font-size:18px; line-height:20px; margin-bottom:15px;"><a style="font-weight: bold;" asp-area="Identity" asp-page="/Account/Register">Signup</a> with us today to join us on this journey.</p>

Views/Home/EMR.cshtml
<link rel="stylesheet" href="~/css/site.css" />
@{
    ViewData["Title"] = "For Corporations";
    @*Layout = "~/Views/Shared/_LayoutForSubPages.cshtml";*@
}

<img src="~/images/emr.jpg" style="width:100%; height:350px; margin-bottom:20px; border-radius:15px;" />

<h1 style="color:#42a5ff; font-size:24px; font-weight:bold">Information to Corporations</h1>
<hr />
<p style="font-size:18px; line-height:20px; margin-bottom:15px;">
    Whether you are a telemedicine company, EMR/EHR company or HMO, all your actions and goals are centred around patient well-being. We help you simplify HIE through a secure, digital health ID that is unique to each patient. Our secure view-only access to the patient health information, not only improves patient satisfaction with your company, but also improves adherence and long-term relationship with physicians and patients. As a telehealth company, both sides of your market, physicians as well as patients will appreciate your commitment to patient well-being.
    As an EMR/EHR company, you have hundreds of millions of patient medical records. All we need is small snippets from there to create our unique health ID. Because our common goal is to make the process of delivery of care hassle-free for the physicians.
    As an HMO, good patient outcomes and stress-free physicians are drivers of your success, and we want to participate with you in value cocreation of sustainable care.
</p>
<p style="font-size:18px; line-height:20px; margin-bottom:15px;"><a style="font-weight: bold;" href="/">Partner with us.</a></p>

Views/Home/FAQ.cshtml
<link rel="stylesheet" href="~/css/accordion.css" />
@{
    ViewData["Title"] = "FAQ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img src="~/images/faq.jpg" style="width:100%; height:350px; margin-bottom:20px; border-radius:15px;" />

<h1 style="color:#42a5ff; font-size:24px; font-weight:bold">We have all the answers to your Questions!</h1>
<hr />
<div class="accordionWrap" style="margin-bottom:55px;">
    <button class="accordion"><h1>1. Why do we need a digital health ID? </h1></button>
    <div class="panel">
        <p>
            Digitization, decentralization and democratisation have been the key steps of technological advances in any field. Healthcare has reached digitization since several years, and with Atom Health we are enabling the democratization and decentralisation of the digitized data.
        </p>
    </div>

    <button class="accordion"><h1>2. Our doctor has all the health data they need and so do we as patients,do we really need Atom Health? </h1></button>
    <div class="panel">
        <p>
            Each doctor in your care process has all the healthcare data generated by him/her. As a patient you may have some access to this information. However, each physician who acts as your caregiver at any point in time, can work in your best interest only when he/she has access to all your vital health information.
        </p>
    </div>

    <button class="accordion"><h1>3. I wear FitBit/or other health monitoring device, isn't that enough for the doctor? </h1></button>
    <div class="panel">
        <p>
            FitBit or other devices can monitor your realtime vitals. But your doctor can make sense of this data only when he/she has the background about your medical history, family history, etc.
        </p>
    </div>

    <button class="accordion"><h1>4. There are repositories that collect all my medical records in one place. How is Atom Health different? </h1></button>
    <div class="panel">
        <p>
            These repositories collect all the medical records in one place, but at the time of providing care, a doctor has very limited time to browse through all those pages of notes, to come to correct diagnosis and management. Atom Health is an extremely concise health information, that carries the most vital health information that any physician can review at the time of providing care, thereby ensuring good patient outcomes.
        </p>
    </div>

    <button class="accordion"><h1>5. Who owns my data? </h1></button>
    <div class="panel">
        <p>
            Physicians are the custodians of all your healthcare information, according to law. Atom Health is decentralized platform, so every "Atom" created by you is owned by you, verified by your family doctor and can be shared with physicians/caregivers/medical insurance companies upon your discretion.
        </p>
    </div>

    <button class="accordion"><h1>6. How many "Atoms" can I create? </h1></button>
    <div class="panel">
        <p>
            You can create an ATOM for each individual in your family. You can group them under family, and thereby have access to 'Atoms" that belong to your dependents- children, senior parents, etc.
        </p>
    </div>

    <button class="accordion"><h1>7. How do I share my health info with the attending physician?</h1></button>
    <div class="panel">
        <p>
            If you're using a telemedicine consult, you can share a "view only" access to your Atom, through a code shared with the consulting physician. Two-factor authentication and one-time-view-only access prevents misuse of data. If you are at a walk-in clinic or emergency, you can use the same, two-factor authentication to share the data with the attending physician.
        </p>
    </div>

    <button class="accordion"><h1>8. Are you HIPAA and PIPEDA compliant? </h1></button>
    <div class="panel">
        <p>
            Yes, We are HIPAA, PIPEDA and PHIA compliant.
        </p>
    </div>
</div>
<script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        });
    }
</script>

Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using AtomHealth.Areas.Identity.Data

@inject SignInManager<AtomHealthUser> SignInManager
@inject UserManager<AtomHealthUser> UserManager

<link rel="stylesheet" href="~/css/site.css" />
@{
    ViewData["Title"] = "Index";

}


    <div class="text-center">
        <img src="~/images/banner.jpg" alt="logoimage" />
    </div>


    <div class="bottom-left">
        <h1>ATOM Health empowers you</h1>
        <p>Every player in the healthcare sector has one common goal- improved patient outcome. We enable that.</p>
        <a href="/">Learn More</a>
    </div>
    <div class="midSector">
        <div class="bottom-bottom">
            <div class="blockBox">
                <h1>Patients</h1><br />
                <p>Your vital healthcare information stored under your unique digital health ID. Owned by you, verified by your family physician and you choose who views it..<a asp-controller="Home" asp-action="Patient" style="font-weight:bold; color:#42a5ff">Learn More</a></p>
            </div>

            <div class="blockBox">
                <h1>Doctors </h1><br />
                <p>Changing times call for newer, functional solutions. As a physician your concern is the best possible outcome for your patients, we take care of the "HOW"..<a asp-controller="Home" asp-action="Doctor" style="font-weight:bold; color:#42a5ff">Learn More</a></p>
            </div>

            <div class="blockBox">
                <h1>Corporations</h1><br />
                <p>Whether you are a telemedicine company, EMR/EHR company or HMO, all your actions and goals are centred around patient well-being. We help you simplify HIE..<a asp-controller="Home" asp-action="EMR" style="font-weight:bold; color:#42a5ff">Learn More</a></p>
            </div>

            <div class="blockBox">
                <h1>Medical insurance companies</h1><br />
                <p>As virtual and in-person care blend into one, improved patient outcome becomes a shared responsibility. We help reduced the burden with a secure, encrypted digital health ID..<a asp-controller="Home" asp-action="Insurance" style="font-weight:bold; color:#42a5ff">Learn More</a></p>
            </div>

        </div>

    </div>

    <div class="welcometext">

        <h1 style="color:#42a5ff; font-size:24px; font-weight:bold">Welcome to ATOM Health</h1>
        <hr />
        <p style="font-size:18px; line-height:20px; margin-bottom:15px;">
            In today's times when technology evolves everyday, a healthcare provider's responsibility extends way beyond providing care. Collaborative care between different specialists is the norm and access to relevant health information is critical to diagnosis and management. At Atom Health, we collect verified vital health information and store it in a secure encrypted digital health ID or "ATOM" of each patient.

    </div>

    <div class="welcometext" style="margin-bottom: 55px;">
        <h1 style="color:#42a5ff; font-size:24px; font-weight:bold">Our Vision</h1>
        <hr />

        <p style="font-size:18px; line-height:20px; margin-bottom:15px;">
            The future of healthcare is a good balance of in-person care and telehealth consults. To make the process seamless, to keep the care uninterrupted and to ensure best possible outcomes, sharing of vital health information in a timely manner is critical. While the physician is the custodian of the medical records, the patient is an aware, responsible citizen who wants to actively participate in maintaining his/her health.
        </p>
        <p style="font-size:18px; line-height:20px; margin-bottom:15px;">
            "Atom" is a unique digital health ID, secure and encrypted, that stores a patient's vital health information, curated with the help of their physician.
        </p>
    </div>

Views/Home/Insurance.cshtml
<link rel="stylesheet" href="~/css/site.css" />
@{
    ViewData["Title"] = "For Insurance";
    @*Layout = "~/Views/Shared/_LayoutForSubPages.cshtml";*@
}

<img src="~/images/insurance.png" style="width:100%; height:350px; margin-bottom:20px; border-radius:15px;" />

<h1 style="color:#42a5ff; font-size:24px; font-weight:bold">Information to Insurance Companies</h1>
<hr />
<p style="font-size:18px; line-height:20px; margin-bottom:15px;">
    As virtual and in-person care blend into one, improved patient outcome becomes a shared responsibility.  Annually, misdiagnosis and complications related to incomplete medical history causes a loss of 20 million DALYs and billions of dollars. We hope to reduce this burden with a secure, encrypted digital health ID. This unique patient health ID can be used to share vital health information with the attending physician, thereby preventing adverse outcomes. We also help coordinate care and claims to streamline the process for you.
</p>
<p style="font-size:18px; line-height:20px; margin-bottom:15px;"><a style="font-weight: bold;" href="/">Partner with us.</a></p>

Views/Home/JoinUs.cshtml
@model AtomHealth.Models.Subscribe
<link rel="stylesheet" href="~/css/site.css" />
@{
    ViewData["Title"] = "Create";
    @*Layout = "~/Views/Shared/_LayoutWithoutBanner.cshtml";*@
}



<h1 style="color:#42a5ff; font-size:24px; font-weight:bold">Join Us</h1>
<hr />
<div class="tabWrap">
    <div class="joinUsBtn">
        <button class="tablink" onclick="openCity(event,'Patients')">Patients</button>
        <button class="tablink" onclick="openCity(event,'Doctors')">Doctors</button>
        <button class="tablink" onclick="openCity(event,'Corporations')">Corporations</button>
        <button class="tablink" onclick="openCity(event,'MIC')">Medical Insurance Companies</button>

    </div>

    <hr />

    <div id="Patients" class="w3-container city">
        <h2>Patients</h2>
        <p>
            Your vital healthcare information stored under your unique digital health ID. Owned by you, verified by your family physician and you choose who views it.
            Sign up with us, create your profile and our software generates a unique digital ID, specific to you. All your vital health information- including your medical conditions, medications, allergies, past medical history, family history, genetic history, is stored securely in this unique digital healthID assigned to you, much like a passport carrying your travel history. You have the view-only access key on you at all times and can share that with another healthcare provider, whether you are doing a virtual consult on telemedicine platform or you are in a walk-in clinic.  What's more? You can add family members or dependents and ensure their well-being too.
            <a asp-controller="SignUpAtom" asp-action="CreateForUserWhoNeedHelp" style="font-weight:bold; color:#42a5ff">SIGN UP</a>  with us today to join us on this journey.
        </p>
    </div>

    <div id="Doctors" class="w3-container city" style="display:none">
        <h2>Doctors</h2>
        <p>
            Changing times call for newer, functional solutions. Virtual care, being peripheral since a long time, suddenly found acceptance and adoption during these unprecedented times.
            As a physician, your Hippocratic Oath puts you in a position where you have to adopt new technology for the patients, while being mindful of their privacy rights, as you pursue your goal of patient well-being and best possible outcomes.
            As you juggle in-person clinical visits and virtual telemedicine visits, we help you maintain your peace of mind by enabling simple, concise health information sharing.
            Improved patient outcomes, reduced liability and more reliable decision-making for a patient are just a few benefits. Ask your telehealth provider to connect with us to enable secure data access.
            <a asp-controller="SignUpAtom" asp-action="CreateForUserWhoNeedHelp" style="font-weight:bold; color:#42a5ff">SIGN UP</a> with us today to join us on this journey.
        </p>
    </div>

    <div id="Corporations" class="w3-container city" style="display:none">
        <h2>Corporations</h2>
        <p>
            Whether you are a telemedicine company, EMR/EHR company or HMO, all your actions and goals are centred around patient well-being. We help you simplify HIE through a secure, digital health ID that is unique to each patient.
            Our secure view-only access to the patient health information, not only improves patient satisfaction with your company, but also improves adherence and long-term relationship with physicians and patients.
            As a telehealth company, both sides of your market, physicians as well as patients will appreciate your commitment to patient well-being.
            As an EMR/EHR company, you have hundreds of millions of patient medical records. All we need is small snippets from there to create our unique health ID.
            Because our common goal is to make the process of delivery of care hassle-free for the physicians.
            As an HMO, good patient outcomes and stress-free physicians are drivers of your success, and we want to participate with you in value cocreation of sustainable care.
            <a asp-controller="Contact" asp-action="Index" style="font-weight:bold; color:#42a5ff">Partner with us</a>
        </p>
    </div>

    <div id="MIC" class="w3-container city" style="display:none">
        <h2>Medical Insurance Companies</h2>
        <p>
            As virtual and in-person care blend into one, improved patient outcome becomes a shared responsibility.  Annually, misdiagnosis and complications related to incomplete medical history causes a loss of 20 million DALYs and billions of dollars.
            We hope to reduce this burden with a secure, encrypted digital health ID. This unique patient health ID can be used to share vital health information with the attending physician, thereby preventing adverse outcomes.
            We also help coordinate care and claims to streamline the process for you.
            <a asp-controller="Contact" asp-action="Index" style="font-weight:bold; color:#42a5ff">Partner with us</a>
        </p>
    </div>
</div>
<hr />




<h1 style="color:#42a5ff; font-size:24px; font-weight:bold">Subscribe for Newsletters</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Subscribe">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                Email Address:
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            @if (ViewBag.msg != null)
            {
                <p style="color:red; font-weight:bold">@ViewBag.msg</p>
            }

            @if (ViewBag.alreadysub != null)
            {
                <p style="color:red; font-weight:bold">@ViewBag.alreadysub</p>
            }
            <div class="form-group">
                <input type="submit" value="Subscribe" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<script>
    function openCity(evt, cityName) {
        var i, x, tablinks;
        x = document.getElementsByClassName("city");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablink");
        for (i = 0; i < x.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" w3-gray", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " w3-gray";
    }
</script>

Views/Home/News.cshtml
@model IEnumerable<AtomHealth.Models.News.Article>
<link rel="stylesheet" href="~/css/news.css" />
<link rel="stylesheet" href="~/css/site.css" />
@{
    ViewData["Title"] = "News";
    @*Layout = "~/Views/Shared/_LayoutWithoutBanner.cshtml";*@
}
<h1>Health News of Canada</h1>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="leftcolumnNews">
            <div class="cardNews">
                <h2>@Html.DisplayFor(modelItem => item.title)</h2>
                <h5>Author:  @Html.DisplayFor(modelItem => item.author)</h5>
                <h5> Date: @Html.DisplayFor(modelItem => item.publishedAt)</h5>
                <p> @Html.DisplayFor(modelItem => item.description)</p>
                <p> @Html.DisplayFor(modelItem => item.content)</p>
                <a href=" @Html.DisplayFor(modelItem => item.url)" target="_blank">Click here to read more..</a>
                <p> Source: @Html.DisplayFor(modelItem => item.source.name)</p>
            </div>
            <div class="fakeimg">
                @if ((item.urlToImage) == null)
                {
                    <img src="~/images/No-image-available.jpg" />
                }
                else
                {
                    <img src="@Html.DisplayFor(modelItem => item.urlToImage)" alt="imageofcontent" />
                }
            </div>
            }
        </div>
    }
</div>

Views/Home/OurSolution.cshtml
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
@{
    ViewData["Title"] = "Our Solution";

}

<img src="~/images/patient.jpg" style="width:100%; height:350px; margin-bottom:20px; border-radius:15px;" />

<h1 style="color:#42a5ff; font-size:24px; font-weight:bold">Our Solution</h1>
<hr />

<p>
    <img src="~/images/OurSolution.png" style="width:100%; height:auto; margin-bottom:50px;" />
</p>

Views/Home/Patient.cshtml
<link rel="stylesheet" href="~/css/site.css" />
@{
    ViewData["Title"] = "For Patients";
    @*Layout = "~/Views/Shared/_LayoutWithoutBanner.cshtml";*@
}

<img src="~/images/patient.jpg" style="width:100%; height:350px; margin-bottom:20px; border-radius:15px; color:black" />

<h1 style="color:#42a5ff; font-size:24px; font-weight:bold">Information to Patients</h1>
<hr />
<p style="font-size:18px; line-height:20px; margin-bottom:15px;">
    Your vital healthcare information stored under your unique digital health ID. Owned by you, verified by your family physician and you choose who views it.
    Sign up with us, create your profile and our software generates a unique digital ID, specific to you. All your vital health information- including your medical conditions, medications, allergies, past medical history, family history, genetic history, is stored securely in this unique digital healthID assigned to you, much like a passport carrying your travel history. You have the view-only access key on you at all times and can share that with another healthcare provider, whether you are doing a virtual consult on telemedicine platform or you are in a walk-in clinic.
    What's more? You can add family members or dependents and ensure their well-being too.
</p>
<p style="font-size: 18px;
        line-height: 20px;
        margin-bottom: 15px;
        color: black"><a style="font-weight: bold;" asp-area="Identity" asp-page="/Account/Register">Signup</a> with us today to join us on this journey.</p>

Views/Home/Services.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>This is SERVICE Page. Work in Progress</h1>